# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
black: true
check_commit_message: true
check_manifest: true
cherry_pick_automation: false
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: false
docs_test: false
plugin_app_label: npm
plugin_camel: PulpNpm
plugin_camel_short: Npm
plugin_caps: PULP_NPM
plugin_caps_short: NPM
plugin_dash: pulp-npm
plugin_dash_short: npm
plugin_name: pulp_npm
plugin_snake: pulp_npm
publish_docs_to_pulpprojectdotorg: true
pulp_settings: null
pulpcore_branch: master
pulpcore_pip_version_specifier: null
pulpprojectdotorg_key_id: null
pydocstyle: false
pypi_username: pulp
redmine_project: npm-plugin
stable_branch: null
test_bindings: false
test_performance: false
test_released_plugin_with_next_pulpcore_release: false
test_s3: true
travis_addtl_services: []
travis_notifications: null
update_redmine: true

