# Manage issues in a project board using https://github.com/leonsteinhaeuser/project-beta-automations

---
name: Kanban
on:
  pull_request_target:
  issues:
    types:
      - labeled
      - reopened
      - assigned
      - closed

env:
  free_to_take: Free to take
  in_progress: In Progress
  needs_review: Needs review

jobs:
  # only prio-list labeled items should be added to the board
  add-to-project-board:
    if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'prio-list') && contains(fromJson('["labeled", "reopened"]'), github.event.action)
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to Free-to-take list
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.RELEASE_TOKEN }}
          user: pulpbot
          project_id: 8
          resource_node_id: ${{ github.event.issue.node_id }}
          operation_mode: status
          status_value: ${{ env.free_to_take }} # Target status

  move-to-inprogress:
    if: github.event_name == 'issues' && github.event.action == 'assigned'
    runs-on: ubuntu-latest
    steps:
      - name: Move an issue to the In Progress column
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.RELEASE_TOKEN }}
          user: pulpbot
          project_id: 8
          resource_node_id: ${{ github.event.issue.node_id }}
          operation_mode: status
          status_value: ${{ env.in_progress }} # Target status

  find-linked-issues:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    name: Find issues linked to a PR
    outputs:
        linked-issues: ${{ steps.linked-issues.outputs.issues }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Linked Issues Action
        uses: kin/gh-action-get-linked-issues@v1.0
        id: linked-issues
        with:
          access-token: ${{ secrets.RELEASE_TOKEN }}
      - name: debug
        id: testing
        run: |
          ISSUES=$(echo '${{ toJSON(steps.linked-issues.outputs ) }}' | jq .issues)
          if [[ "$ISSUES" == "[]" ]]; then
            echo "aaaaaa"
          fi
          echo $ISSUES
          echo "bbbbbbb"
          echo '${{ toJSON(steps.linked-issues.outputs.issues ) }}'

  move-to-needs-review:
    if: github.event_name == 'pull_request_target' && contains(needs.find-linked-issues.outputs.linked-issues.*.issue.state, 'open')
    runs-on: ubuntu-latest
    name: Move linked issues to Needs Review
    needs: find-linked-issues
    strategy:
      matrix:
        issues: ${{ fromJSON(needs.find-linked-issues.outputs.linked-issues) }}
    steps:
      - name: Move to Needs Review
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.RELEASE_TOKEN }}
          user: pulpbot
          project_id: 8
          resource_node_id: ${{ matrix.issues.issue.node_id }}
          operation_mode: status
          status_value: ${{ env.needs_review }} # Target status

  move-to-done:
    if: github.event_name == 'issues' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Move an issue to the Done column
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.RELEASE_TOKEN }}
          user: pulpbot
          project_id: 8
          resource_node_id: ${{ github.event.issue.node_id }}
          operation_mode: status
          status_value: ${{ env.done }} # Target status
