name: Publish docs

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
      redis:
        image: redis
    env:
      TEST: 'docs'
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Before Install
        run: .github/workflows/scripts/before_install.sh
        shell: bash
      - name: Install
        run: |
          .github/workflows/scripts/install.sh
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        shell: bash
      - name: Before Script
        run: |
          .github/workflows/scripts/before_script.sh
      - name: Publish Docs
        env:
          PULP_DOCS_KEY: ${{ secrets.PULP_DOCS_KEY }}
        run: .github/workflows/scripts/publish_docs.sh
      - name: After failure
        if: failure()
        run: |
          http --timeout 30 --check-status --pretty format --print hb http://pulp/pulp/api/v3/status/ || true
          docker images || true
          docker ps -a || true
          docker logs pulp || true
          docker exec pulp ls -latr /etc/yum.repos.d/ || true
          docker exec pulp cat /etc/yum.repos.d/* || true
